stages:
  - deploy


include:
  template: Jobs/Secret-Detection.gitlab-ci.yml


variables:
  VAULT_SERVER_URL: https://ci.diplomproj.ru:8200


image:
  name: hashicorp/terraform:latest
  entrypoint: [""]

update_amazon_infrastructure:
  before_script:
    - terraform init
    - terraform state pull > terraform.tfstate
  stage: deploy
  when: manual
  secrets:
    domain:
      vault: secret/infra/domain
    cloudflare_zone_id:
      vault: secret/infra/cloudflare_zone_id
    aws_zone:
      vault: secret/infra/aws_zone
    cloudflare_api_token:
      vault: secret/infra/cloudflare_api_token
    email:
      vault: secret/infra/email
  script:
    - terraform plan
    - >
      terraform apply --auto-approve -var="domain=$domain" -var="cloudflare_zone_id=$cloudflare_zone_id"
      -var="aws_zone=$aws_zone" -var="cloudflare_api_token=$cloudflare_api_token" -var="email=$email"
