stages:
  - deploy

variables:
  domain: $domain
  cloudflare_zone_id: $cloudflare_zone_id
  aws_zone: $aws_zone
  cloudflare_api_token: $cloudflare_api_token
  email: $email
  TFE_TOKEN: $terraform_token



image:
  name: hashicorp/terraform:latest
  entrypoint: [""]

update_amazon_infrastructure:
  before_script:
  stage: deploy
  script:
    - terraform init
    - terraform apply


destroy_amazon_infrastructure:
  stage: deploy
  when: manual
  script:
    - terraform init
    - terraform destroy
