stages:
  - deploy

variables:
  domain: $domain
  cloudflare_zone_id: $cloudflare_zone_id
  aws_zone: $aws_zone
  cloudflare_api_token: $cloudflare_api_token
  email: $email

image:
  name: hashicorp/terraform:latest
  entrypoint: [""]

update_amazon_infrastructure:
  before_script:
    - terraform init
    - terraform state pull > terraform.tfstate
  stage: deploy
  when: manual
  script:
    - >
      terraform plan -var="domain=$domain" -var="cloudflare_zone_id=$cloudflare_zone_id"
      -var="aws_zone=$aws_zone" -var="cloudflare_api_token=$cloudflare_api_token" -var="email=$email"
    - >
      terraform apply --auto-approve -var="domain=$domain" -var="cloudflare_zone_id=$cloudflare_zone_id"
      -var="aws_zone=$aws_zone" -var="cloudflare_api_token=$cloudflare_api_token" -var="email=$email"


destroy_amazon_infrastructure:
  before_script:
    - terraform state pull > terraform.tfstate
    - terraform init
  stage: deploy
  when: manual
  script:
    - >
      terraform plan -var="domain=$domain" -var="cloudflare_zone_id=$cloudflare_zone_id"
      -var="aws_zone=$aws_zone" -var="cloudflare_api_token=$cloudflare_api_token" -var="email=$email"

    - >
      terraform destroy --auto-approve -var="domain=$domain" -var="cloudflare_zone_id=$cloudflare_zone_id"
      -var="aws_zone=$aws_zone" -var="cloudflare_api_token=$cloudflare_api_token" -var="email=$email"