stages:
  - deploy

image:
  name: hashicorp/terraform:latest
  entrypoint: [""]

update_amazon_infrastructure:
  before_script:
  stage: deploy
  variables:
    TFE_TOKEN: $terraform_token
  script:
    - terraform init
    - terraform apply


destroy_amazon_infrastructure:
  stage: deploy
  when: manual
  variables:
    TFE_TOKEN: $terraform_token
  script:
    - terraform init
    - terraform destroy
