stages:
  - deploy

image: hashicorp/terraform:latest
entrypoint: [""]

update_amazon_infrastructure:
  before_script:
    - terraform init
    - terraform state pull > terraform.tfstate
  stage: deploy
  when: manual
  script:
    - terraform plan
    - terraform apply --auto-approve