stages:
  - deploy

image:
  name: hashicorp/terraform:latest
  entrypoint: [""]

update_amazon_infrastructure:
  stage: deploy
  when: manual
  script:
    - >
      echo "credentials "app.terraform.io" {
      token = \"$TFE_TOKEN\"
      }" > ~/.terraformrc
    - terraform init
    - terraform apply --auto-approve


destroy_amazon_infrastructure:
  stage: deploy
  when: manual
  script:
    - >
      echo "credentials "app.terraform.io" {
      token = \"$TFE_TOKEN\"
      }" > ~/.terraformrc
    - terraform init
    - terraform destroy --auto-approve
